networks:
  web:
    external: true

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutreai-landing
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NEXT_PUBLIC_API_URL=https://service-789.nutre.ai
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.rule=Host(`nutre.ai`)
      - traefik.http.routers.landing.entrypoints=websecure
      - traefik.http.routers.landing.tls=true
      - traefik.http.routers.landing.tls.certresolver=letsencrypt
      - traefik.http.services.landing.loadbalancer.server.port=3002
